{% set name = "photochem" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem/releases/download/v{{ version }}/photochem-{{ version }}_withdata.tar.gz
  sha256: fe5935c7740dddcff3b9c3f866ad122a8529973635acf0f2a16a1bb786cc3413

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build
    - numpy
    - cython
    - ninja
    - pkgconfig
    - zlib
    - hdf5
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - numba

test:
  imports:
    - photochem
    - photochem.clima

about:
  home: https://github.com/Nicholaswogan/photochem
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A chemical model of planetary atmospheres

extra:
  recipe-maintainers:
    - Nicholaswogan
