{% set name = "photochem" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem/releases/download/v{{ version }}/photochem-{{ version }}_withdata.tar.gz
  sha256: 3e7f2af3c61ccce1cd8256bdc7271c74d4ed694fe6b3b40ed694320f0ba029f3

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - fypp                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build
    - numpy
    - cython
    - ninja
    - pkgconfig
    - zlib
    - hdf5
    - fypp
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - numba

test:
  imports:
    - photochem
    - photochem.clima

about:
  home: https://github.com/Nicholaswogan/photochem
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A chemical model of planetary atmospheres

extra:
  recipe-maintainers:
    - Nicholaswogan
