{% set name = "photochem" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem/archive/v{{ version }}.tar.gz
  sha256: dd1d3775df43ab34f817495189757b883152d0df2caed518f87954ca68f8ec97

build:
  skip: true  # [win]
  number: 0
  ignore_run_exports:
    - libzlib
    - python
    - libcxx
    - numpy

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - fypp                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - cmake <4.0
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build
    - numpy
    - cython
    - ninja
    - pkgconfig
    - zlib
    - hdf5
    - fypp
    - libblas
    - libcblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgcc  # [osx and x86_64]
  run:
    - python
    - photochem_clima_data ==0.3.1
    - scipy
    - pyyaml
    - numba
    - h5py
    - astropy-base
    - astroquery
    - threadpoolctl
    - requests
    - libgcc  # [osx and x86_64]
    - blis      # [linux]
    - mkl       # [linux]

test:
  imports:
    - photochem
    - photochem.clima
    - photochem.equilibrate

about:
  home: https://github.com/Nicholaswogan/photochem
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE
  summary: A chemical model of planetary atmospheres

extra:
  recipe-maintainers:
    - Nicholaswogan
